# Site settings
baseurl = "https://cereus-pro.netlify.com/"
languageCode = "id-ID"
title = "Cereus Pro | Hugo Theme"

#Set googleAnalytics ID
googleAnalytics = ""
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "arhen"
	description = "Minimalist Blog Themes For Developer"
	bio = "Blazing Fast & Minimalist Blog Themes"

	twitter = "arhen_desu"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "" #disqus shortname here


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = "images/avatar.jpg"

	# Add custom assets with their paths relative to the static folder
	customCSS = ['css/custom.css']
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	now = ""
	blogs = ""
	tags = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "Opps! This place is called 404."
	subtitle404 = "You entered in the wrong room buddy! Go back."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

	githubRepo = ""

# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/arhen_desu"
	github-square = "https://www.github.com/arhen"
	linkedin-square = "https://www.linkedin.com/in/rahmadslamet"
